/**
 * Vibe Stealth — frozen interface contract (v0.1.0).
 *
 * Every module in this codebase depends on these types. Behavioral pins that
 * cannot be expressed in the type system live in docs/CONTRACT.md — read it
 * before implementing against this file. This file is the frozen interface contract.
 *
 * Layering rule: nothing under src/core/ or src/providers/ may import 'vscode'.
 * Only src/ui/ and src/extension.ts may.
 */

// ---------------------------------------------------------------------------
// Domain model
// ---------------------------------------------------------------------------

export type SportKind =
  | 'baseball'
  | 'basketball'
  | 'football'
  | 'hockey'
  | 'soccer'
  | 'esports'
  | 'other';

/** pre = not started; in = live; post = finished; unknown = unparsable status. */
export type GamePhase = 'pre' | 'in' | 'post' | 'unknown';

/**
 * Absolute https URLs to a logo image (CONTRACT §13). Providers supply URLs only;
 * they never fetch images. The UI's logoCache downloads, validates and caches them.
 */
export interface LogoRef {
  light: string;
  /** Dark-theme variant when the source offers one; else the UI reuses `light`. */
  dark?: string;
}

export interface League {
  /** Provider-scoped stable id, e.g. 'nba', 'eng.1', 'mlb', 'nhl', 'lol'. */
  id: string;
  providerId: string;
  /** English display name; UI may localize known ids. */
  name: string;
  sport: SportKind;
  logo?: LogoRef;
}

export interface TeamSide {
  /** Provider-native team id; '' if unknown. */
  id: string;
  /**
   * Best display name the provider offers (NHL score/now only carries the
   * nickname, e.g. 'Stars'). Never empty — fall back to abbrev or 'TBD'.
   */
  name: string;
  /** Short code ≤ 5 chars for status bar / line tags, e.g. 'STL'. Derived from name if absent. */
  abbrev: string;
  /**
   * Integer ≥ 0, or undefined when unknown/unparsable. Providers must coerce
   * string scores; coercion failure ⇒ undefined, never NaN or negative.
   */
  score: number | undefined;
  /** CONTRACT §13. Omitted when the provider has no logo for this team. */
  logo?: LogoRef;
}

export interface Game {
  /** Globally unique: `${providerId}:${leagueId}:${nativeGameId}`. */
  id: string;
  providerId: string;
  leagueId: string;
  leagueName: string;
  sport: SportKind;
  /** ISO-8601 UTC with seconds ('2026-07-08T19:45:00Z'), or undefined if unparsable. */
  startTimeUtc: string | undefined;
  phase: GamePhase;
  /** Human status, locale-neutral, e.g. 'Top 7th', 'Q3 04:12', "67'", 'Final'. Never empty. */
  statusText: string;
  /** ≤ 8 chars for the status bar, e.g. 'T7', 'Q3', "67'", 'FT', 'HT', 'G2'. Never empty. */
  statusShort: string;
  home: TeamSide;
  away: TeamSide;
}

export type PlayEventKind =
  | 'play' // ordinary play-by-play line
  | 'score' // a play that changed the score
  | 'status' // period/inning/game boundary ('End of the 9th', 'Game Final')
  | 'correction' // re-emission of an already-emitted event whose text changed
  | 'system'; // lines generated by the relay itself (backfill notice, errors…)

export interface PlayEvent {
  /**
   * Stable within a game. Providers use native ids when stable; otherwise
   * derive as documented in docs/CONTRACT.md §Providers. Never empty.
   */
  id: string;
  gameId: string;
  /**
   * Monotonic ordering key within the game's full event list (array index or
   * native sort key per docs/CONTRACT.md). Ties broken by id (lexicographic).
   */
  sequence: number;
  /** Display clock within period, e.g. '04:12', or undefined (baseball). */
  clock: string | undefined;
  /** Display period label, e.g. 'Q3', 'P2', '7회말', 'T7', or undefined. */
  period: string | undefined;
  /** Single line of prose. Non-empty, no control chars, no newlines, ≤ 500 chars. */
  text: string;
  kind: PlayEventKind;
  /** Present when the provider knows the score as of this event. */
  scoreAfter: { home: number; away: number } | undefined;
}

// ---------------------------------------------------------------------------
// Provider SPI
// ---------------------------------------------------------------------------

export type ProviderErrorKind =
  | 'network' // DNS/timeout/abort/5xx — retryable with backoff
  | 'rate-limit' // 429 — retry after retryAfterMs (or ≥ 60s)
  | 'auth' // 401/403 — stop polling provider until credentials change
  | 'parse' // JSON invalid or shape assumptions broken — retryable, log payload head
  | 'not-found' // 404 — game/league vanished
  | 'unavailable'; // other non-retryable (4xx misc, oversize body)

export class ProviderError extends Error {
  constructor(
    public readonly kind: ProviderErrorKind,
    message: string,
    public readonly retryAfterMs?: number,
    /** First ≤ 300 chars of the offending payload, for diagnostics. */
    public readonly payloadHead?: string,
  ) {
    super(message);
    this.name = 'ProviderError';
  }
}

/** Everything a provider may touch of the outside world. No other IO allowed. */
export interface ProviderContext {
  /** Resolved UI locale — LoL Esports uses it for the `hl` param. */
  readonly locale: RelayLocale;
  /**
   * Live value of the gameState setting. A provider whose state costs an EXTRA
   * request (LoL Esports' livestats window) MUST skip that request when false.
   * State that is free from the play payload (MLB, ESPN soccer) may ignore it —
   * the UI won't render it. Read fresh each call (getter), so a settings change
   * takes effect on the next poll without a reload.
   */
  readonly gameStateEnabled: boolean;
  /**
   * Live value of the detail setting (CONTRACT §12). 'summary' reproduces the
   * v0.2 event lists exactly; 'detailed' adds provider-composed, LOCALIZED lines
   * (MLB pitch-by-pitch, NHL shots/hits). API prose is never translated (§12.1).
   * Read fresh each call (getter) so a change takes effect on the next poll.
   */
  readonly detail: DetailLevel;
  /**
   * GET url, parse JSON. Throws ProviderError only (never raw errors).
   * Timeout 10s, body cap 8 MiB, UA 'vibe-stealth-vscode/<version>'.
   */
  fetchJson(url: string, headers?: Record<string, string>): Promise<unknown>;
  /** Secret lookup (e.g. 'pandascore.token'); undefined when unset. */
  getSecret(key: string): Promise<string | undefined>;
  /** Diagnostics sink (never user-facing relay lines). */
  log(message: string): void;
  /** Milliseconds since epoch — injectable for tests. */
  now(): number;
}

export interface PlaySnapshot {
  /** Fresh game state (score/phase/status may have advanced). */
  game: Game;
  /**
   * The FULL list of currently-known events for the game, ordered by sequence
   * ascending. RelayEngine does the diffing; providers never diff.
   */
  events: PlayEvent[];
  /**
   * Live "current state" SNAPSHOT (bases/count, lineups, draft) — the whole
   * value is replaced each poll and rendered ONLY in the tree, NEVER as relay
   * events (it is mutable; the relay is append-only). undefined when the
   * provider has no state for this game (wrong sport, pre-game, or feature off).
   * See CONTRACT §11.
   */
  state?: GameState;
}

// ---------------------------------------------------------------------------
// Live "current state" — a mutable snapshot, distinct from the PlayEvent
// stream. Replaced wholesale each poll; rendered as tree children only.
// ---------------------------------------------------------------------------

/** One batter in a batting order, or one player in a soccer XI. */
export interface LineupSpot {
  /** 1-based order (batting slot, or shirt position index). */
  order: number;
  /** Full display name; never empty. */
  name: string;
  /** Position code, e.g. 'SS', 'C', 'LF' (baseball) / 'G', 'LB' (soccer). '' if unknown. */
  position: string;
  /** Jersey/shirt number as text, or undefined. */
  jersey?: string;
}

export interface BaseballState {
  kind: 'baseball';
  balls: number; // 0–4 defensively clamped
  strikes: number; // 0–3
  outs: number; // 0–3
  /** Runner display name on each base, or undefined when empty. */
  bases: { first?: string; second?: string; third?: string };
  atBat?: string;
  onDeck?: string;
  pitcher?: string;
  /** Batting orders; either may be empty when not yet posted. */
  lineups: { home: LineupSpot[]; away: LineupSpot[] };
}

export interface SoccerState {
  kind: 'soccer';
  home: { formation?: string; starters: LineupSpot[]; bench: LineupSpot[] };
  away: { formation?: string; starters: LineupSpot[]; bench: LineupSpot[] };
}

/** One drafted champion in a LoL composition. */
export interface DraftPick {
  /** 'top' | 'jungle' | 'mid' | 'bottom' | 'support' (lowercased); '' if unknown. */
  role: string;
  /** Champion name as the feed gives it, e.g. 'Vayne', 'JarvanIV'. Never empty. */
  champion: string;
  /** Player/summoner display name; '' if unknown. */
  player: string;
}

export interface EsportsState {
  kind: 'esports';
  /** Game patch, e.g. '16.13'; undefined if unknown. */
  patch?: string;
  blue: { teamCode: string; picks: DraftPick[] };
  red: { teamCode: string; picks: DraftPick[] };
  /** Live totals from the latest frame, when non-zero/known. */
  gold?: { blue: number; red: number };
  kills?: { blue: number; red: number };
}

export type GameState = BaseballState | SoccerState | EsportsState;

export interface SportProvider {
  /** 'espn' | 'mlb' | 'nhl' | 'naver' | 'lolesports' | 'pandascore'. */
  readonly id: string;
  readonly displayName: string;
  /** True ⇒ provider is hidden until its secret exists (see CONTRACT §PandaScore). */
  readonly requiresSecret: string | undefined;
  /** Static or cheap; called at activation and on manual refresh. */
  listLeagues(ctx: ProviderContext): Promise<League[]>;
  /** Current scoreboard window for one league (provider-defined "today"). */
  listGames(ctx: ProviderContext, league: League): Promise<Game[]>;
  /**
   * Full snapshot for one game. May populate PlaySnapshot.state with live
   * "current state" (bases/count, lineups, draft) when the provider and sport
   * support it and gameState is enabled — see CONTRACT §11. Providers without
   * state leave it undefined.
   */
  fetchPlays(ctx: ProviderContext, game: Game): Promise<PlaySnapshot>;
}

// ---------------------------------------------------------------------------
// Relay engine (pure — no IO, no timers)
// ---------------------------------------------------------------------------

export interface RelayEmission {
  /** Events to append to the relay, already ordered for display. */
  events: PlayEvent[];
  /** Game snapshot after this ingest (drives status bar / tree). */
  game: Game;
  /** True when home/away score differs from the previous ingest. */
  scoreChanged: boolean;
  /**
   * Set when phase transitioned this ingest (e.g. 'in' → 'post').
   * Pinned: undefined on the first-ever ingest — the final-score system line
   * fires on the FIRST ingest whose phase is 'post' (see CONTRACT §3.8), not
   * on transitions.
   */
  phaseTransition: { from: GamePhase; to: GamePhase } | undefined;
  /**
   * Passed through UNCHANGED from the ingested PlaySnapshot.state. The engine
   * never diffs or emits it — the UI stashes it on the followed entry and the
   * tree renders it (CONTRACT §11). undefined when the snapshot had no state.
   */
  state?: GameState;
}

export interface RelayEngineOptions {
  /** Max events emitted on first ingest of a game (older ones summarized). */
  backfillLimit: number;
  /** Locale for engine-generated system lines ('en' | 'ko'). */
  locale: RelayLocale;
}

export interface RelayEngine {
  /** Idempotent per snapshot; returns only never-before-emitted lines. */
  ingest(snapshot: PlaySnapshot): RelayEmission;
}

export type RelayLocale = 'en' | 'ko';

/** CONTRACT §12: how granular the relay's event stream is. */
export type DetailLevel = 'summary' | 'detailed';

// ---------------------------------------------------------------------------
// Poll scheduler (owns timers; injectable clock for tests)
// ---------------------------------------------------------------------------

export interface PollPolicy {
  /** Seconds between polls while phase === 'in'. Clamped 10–120, default 20. */
  liveSeconds: number;
  /** Seconds between polls while phase === 'pre'. Fixed 60 (20 within 2 min of start). */
  preSeconds: number;
  /** Global max concurrent in-flight fetches across all games. Fixed 4. */
  maxConcurrent: number;
  /** Backoff: min(interval · 2^failures, 300s); rate-limit ⇒ max(retryAfterMs, 60s). */
  maxBackoffSeconds: number;
}

/**
 * Persisted in workspaceState. Array order IS follow order (append on follow,
 * remove on unfollow, re-follow moves the entry to the end). No cross-reload
 * relay dedup state is persisted: a restored follow gets a FRESH RelayEngine
 * and its first ingest is governed by the backfill cap.
 */
export interface FollowedGameState {
  gameId: string;
  providerId: string;
  leagueId: string;
  /** Epoch ms of the follow action. */
  followedAt: number;
  /** Epoch ms when the game was first observed phase==='post' (0 = not yet). */
  postObservedAt: number;
  /** Last-known display snapshot; renders tree/status bar after reload before first fetch. */
  lastKnown: {
    awayAbbrev: string;
    homeAbbrev: string;
    awayScore: number | undefined;
    homeScore: number | undefined;
    statusShort: string;
    phase: GamePhase;
  };
}

// ---------------------------------------------------------------------------
// Module seams — implemented by the files named in CONTRACT.md §10. These
// interfaces exist so four tasks can build in parallel and link on first try.
// ---------------------------------------------------------------------------

export interface SchedulerTimers {
  setTimeout(fn: () => void, ms: number): unknown;
  clearTimeout(handle: unknown): void;
  now(): number;
}

/** Global fetch-concurrency gate (CONTRACT §4: max 4). */
export interface Semaphore {
  /** Resolves with a release function; callers MUST release in finally. */
  acquire(): Promise<() => void>;
}

export interface GamePollerCallbacks {
  /** Bound closure over (provider, ctx, game). Throws ProviderError only. */
  fetchSnapshot(): Promise<PlaySnapshot>;
  /** Every ingest result (even with zero events — status bar reads game). */
  onEmission(emission: RelayEmission): void;
  /** Poller-generated system lines, as i18n keys (§5) — UI translates+appends. */
  onSystemLine(key: string, params?: Record<string, string | number>): void;
  /** Fired by the post+10min one-shot, or 3× not-found. UI removes the follow. */
  onAutoUnfollow(): void;
  /** Diagnostics channel sink (stacks, payload heads). */
  onDiagnostic(message: string): void;
}

export interface GamePoller {
  start(): void;
  /** Idempotent; cancels all pending timers including the auto-unfollow one-shot. */
  stop(): void;
}

export interface GamePollerOptions {
  engine: RelayEngine;
  initialPhase: GamePhase;
  startTimeUtc: string | undefined;
  /** Already clamped by the caller (CONTRACT §4). */
  liveSeconds: number;
  timers: SchedulerTimers;
  semaphore: Semaphore;
  callbacks: GamePollerCallbacks;
  /** True while the game's provider is auth-blocked (keyed providers only). */
  isProviderBlocked?: () => boolean;
}

export interface FormatOptions {
  locale: RelayLocale;
  showEmoji: boolean;
  /** True when more than one game is followed — adds the [AWY-HOM] tag. */
  multiGame: boolean;
  now(): number;
}

// ---------------------------------------------------------------------------
// UI identifiers & settings keys (single source of truth — package.json must match)
// ---------------------------------------------------------------------------

export const IDS = {
  viewContainer: 'vibeStealth',
  gamesView: 'vibeStealth.games',
  relayChannel: 'Vibe Stealth Relay',
  diagChannel: 'Vibe Stealth Diagnostics',
  commands: {
    refreshGames: 'vibeStealth.refreshGames',
    followGame: 'vibeStealth.followGame',
    unfollowGame: 'vibeStealth.unfollowGame',
    openRelay: 'vibeStealth.openRelay',
    clearRelay: 'vibeStealth.clearRelay',
    pickFollowed: 'vibeStealth.pickFollowed',
    setPandascoreToken: 'vibeStealth.setPandascoreToken',
  },
  settings: {
    locale: 'vibeStealth.locale', // 'auto' | 'en' | 'ko', default 'auto'
    pollSecondsLive: 'vibeStealth.pollSecondsLive', // default 20, clamp 10–120
    pollSecondsScoreboard: 'vibeStealth.pollSecondsScoreboard', // default 60, clamp 30–600
    backfillLimit: 'vibeStealth.backfillLimit', // default 10, clamp 0–100
    maxFollowedGames: 'vibeStealth.maxFollowedGames', // default 6, clamp 1–12
    statusBarEnabled: 'vibeStealth.statusBar.enabled', // default true
    relayShowEmoji: 'vibeStealth.relay.showEmoji', // default true
    gameStateEnabled: 'vibeStealth.gameState.enabled', // default true — live-state tree rows
    detail: 'vibeStealth.detail', // 'summary' (default) | 'detailed' — CONTRACT §12
    logosEnabled: 'vibeStealth.logos.enabled', // default true — CONTRACT §13
    enabledLeagues: 'vibeStealth.leagues.enabled', // string[] of `${providerId}:${leagueId}`; [] = defaults
  },
  secrets: {
    pandascoreToken: 'pandascore.token',
  },
  state: {
    followedGames: 'vibeStealth.followedGames', // FollowedGameState[] in workspaceState
  },
} as const;
